        item = self.random_item()
        monster = self.random.enemy()
        keuken = Room('keuken', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        woonkamer = Room('woonkamer', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        eetkamer = Room('eetkamer', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        badkamer = Room('badkamer', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        gang = Room('gang', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        balkon = Room('balkon', self, item, monster) #!
        item = self.random_item()
        monster = self.random.enemy()
        tuin = Room('tuin', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        bibliotheek = Room('bibliotheek', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        slaapkamer = Room('slaapkamer', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        hobbykamer = Room('hobbykamer', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        fitnessruimte = Room('fitnessruimte', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        studeerkamer = Room('studeerkamer', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        serre = Room('serre', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        garage = Room('garage', self, item, monster)
        item = self.random_item()
        monster = self.random.enemy()
        kelder = Room('kelder', self, item, monster) #!
        item = self.random_item()
        monster = self.random.enemy()
        zolder = Room('zolder', self, item, monster) #!
        
        self.add_room(keuken)
        self.add_room(woonkamer)
        self.add_room(eetkamer)
        self.add_room(badkamer)
        self.add_room(gang)
        self.add_room(balkon)
        self.add_room(tuin)
        self.add_room(bibliotheek)
        self.add_room(slaapkamer)
        self.add_room(hobbykamer)
        self.add_room(fitnessruimte)
        self.add_room(studeerkamer)
        self.add_room(serre)        
        self.add_room(garage)
        self.add_room(kelder)
        self.add_room(zolder)
        
        
        
        item = self.random_item()
        keuken = Room('keuken', self, item)
        self.add_room(keuken)
        item = self.random_item()
        woonkamer = Room('woonkamer', self, item)
        self.add_room(woonkamer)
        item = self.random_item()
        eetkamer = Room('eetkamer', self, item)
        self.add_room(eetkamer)
        item = self.random_item()
        badkamer = Room('badkamer', self, item)
        self.add_room(badkamer)
        item = self.random_item()
        gang = Room('gang', self, item)
        self.add_room(gang)
        item = self.random_item()
        balkon = Room('balkon', self, item) #!
        self.add_room(balkon)
        item = self.random_item()
        tuin = Room('tuin', self, item)
        self.add_room(tuin)
        item = self.random_item()
        bibliotheek = Room('bibliotheek', self, item)
        self.add_room(bibliotheek)
        item = self.random_item()
        slaapkamer = Room('slaapkamer', self, item)
        self.add_room(slaapkamer)
        item = self.random_item()
        hobbykamer = Room('hobbykamer', self, item)
        self.add_room(hobbykamer)
        item = self.random_item()
        fitnessruimte = Room('fitnessruimte', self, item)
        self.add_room(fitnessruimte)
        item = self.random_item()
        studeerkamer = Room('studeerkamer', self, item)
        self.add_room(studeerkamer)
        item = self.random_item()
        serre = Room('serre', self, item)
        self.add_room(serre)
        item = self.random_item()
        garage = Room('garage', self, item)
        self.add_room(garage)
        item = self.random_item()
        kelder = Room('kelder', self, item) #!
        self.add_room(kelder)
        item = self.random_item()
        zolder = Room('zolder', self, item) #!
        self.add_room(zolder)
        